dev.new()
custom_boxplot(data, "Var1", main = "Custom Boxplot for Var1", ylab = "Var1 Values",color = "darkgreen")
dev.new()
custom_boxplot(data, "Var2", main = "Custom Boxplot for Var2", ylab = "Var2 Values",color = "darkgreen")
dev.new()
custom_boxplot(data, "Var3", main = "Custom Boxplot for Var3", ylab = "Var3 Values",color = "darkgreen")
dev.new()
custom_boxplot(data, "Var4", main = "Custom Boxplot for Var4", ylab = "Var4 Values",color = "darkgreen")
dev.new()
custom_boxplot(data, "Var5", main = "Custom Boxplot for Var5", ylab = "Var5 Values",color = "darkgreen")
dev.new()
custom_boxplot(data, "Var6", main = "Custom Boxplot for Var6", ylab = "Var6 Values",color = "darkgreen")
dev.new()
custom_boxplot(data, "Var7", main = "Custom Boxplot for Var7", ylab = "Var7 Values",color = "darkgreen")
dev.new()
custom_boxplot(data, "Var8", main = "Custom Boxplot for Var8", ylab = "Var8 Values",color = "darkgreen")
